version: '3.3'
services:
    alist:
        image: 'xhofe/alist:latest'
        container_name: alist
        network_mode: host
        volumes:
            - '/other/Configs/alist:/opt/alist/data'
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        restart: unless-stopped
