services:
  clash-master:
    image: foru17/clash-master:latest
    container_name: clash-master
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "3000:3000" # Web UI
      - "3001:3001" # API
      - "3002:3002" # WebSocket
    volumes:
      - /other/Configs/clash-master:/app/data
    environment:
      - NODE_ENV=production
      # 外部端口（可选，默认即为 3000/3001/3002）
      - WEB_EXTERNAL_PORT=3000
      - API_EXTERNAL_PORT=3001
      - WS_EXTERNAL_PORT=3002
      - DB_PATH=/app/data/stats.db
