version: '2.3' 
services:
  nginx:
      image: nginx:latest
      container_name: embyng
      network_mode: host
      volumes:
        - /other/Configs/nginx/conf.d:/etc/nginx/conf.d
        - /other/Configs/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /other/Configs/nginx/embyCache:/var/cache/nginx/emby
        - /other/Configs/nginx/logs:/var/log/nginx
      restart: unless-stopped
