#!/bin/bash /etc/rc.common

START=100
STOP=9

start(){
	sleep 5
	nohup sleep 5&&rclone mount aliyunwebdav:/ /disk/ssda/Public/aliyun --cache-dir /disk/ssda/Caches/rclone --allow-other --vfs-cache-mode writes --allow-non-empty --header "Referer:https://www.aliyundrive.com/" &
}

stop(){
	pgrep 'rclone'|xargs kill -9
	fusermount -u /disk/ssda/Public/aliyun
}

restart(){
	stop
	sleep 2s
	start
}
